#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-flowproxy.json" ] && {
    cat > /usr/share/ucitrack/luci-app-flowproxy.json << EEOF
{
    "config": "flowproxy",
    "init": "flowproxy"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@flowproxy[-1]
	add ucitrack flowproxy
	set ucitrack.@flowproxy[-1].init=flowproxy
	commit ucitrack
EOF

/etc/init.d/flowproxy enabled || /etc/init.d/flowproxy enable 2>/dev/null

rm -f /tmp/luci-indexcache* 2>/dev/null
rm -f /tmp/luci-modulecache/* 2>/dev/null

exit 0
